import { Product } from "@/types/product"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Tikka T3x Lite Polyfade",
    brand: "Tikka",
    category: "Karabini",
    sku: "T3X-LP-308",
    price: 1450.0,
    status: "new",
    isRegulated: true,
    image: "/images/products/tikka-t3x.png",
    galleryImages: [
      "/images/products/tikka-t3x.png",
      "/images/products/beretta-686.png",
      "/images/categories/weapons.png",
    ],
    shortDescription:
      "Lagan lovački karabin s provjerenom ergonomijom, namijenjen kupcima koji ispunjavaju zakonske uvjete.",
    availabilityLabel: "Provjera dokumentacije",
    purchaseNote: "Kupnja isključivo u poslovnici uz važeću dokumentaciju.",
    metadata: [
      { label: "Kalibar", value: ".308 Win" },
      { label: "Cijev", value: "510 mm" },
      { label: "Težina", value: "2.8 kg" },
      { label: "Okidanje", value: "Podesivo (1-2 kg)" },
    ],
  },
  {
    id: "2",
    name: "Vortex Venom 5-25x56 FFP",
    brand: "Vortex",
    category: "Optike",
    sku: "VOR-VEN-525",
    price: 680.0,
    salePrice: 599.0,
    status: "sale",
    isRegulated: false,
    image: "/images/products/vortex-venom.png",
    galleryImages: [
      "/images/products/vortex-venom.png",
      "/images/products/pulsar-krypton.png",
      "/images/categories/optics.png",
    ],
    shortDescription:
      "Optika za precizno promatranje s jasnom slikom, čvrstim kućištem i podrškom pri odabiru montaže.",
    availabilityLabel: "Na zalihi",
    metadata: [
      { label: "Povećanje", value: "5-25x" },
      { label: "Promjer leće", value: "56 mm" },
      { label: "Tubus", value: "34 mm" },
      { label: "Končanica", value: "EBR-7C (MRAD)" },
    ],
  },
  {
    id: "3",
    name: "Beretta 686 Silver Pigeon I",
    brand: "Beretta",
    category: "Sačmarice",
    sku: "BER-686-SP",
    price: 2100.0,
    status: "in_stock",
    isRegulated: true,
    image: "/images/products/beretta-686.png",
    galleryImages: [
      "/images/products/beretta-686.png",
      "/images/products/tikka-t3x.png",
      "/images/categories/weapons.png",
    ],
    shortDescription:
      "Klasična sačmarica s naglaskom na pouzdanu izradu i kupnju uz prethodnu provjeru uvjeta.",
    availabilityLabel: "Provjera dokumentacije",
    purchaseNote: "Preuzimanje nakon potvrde dokumentacije u poslovnici.",
    metadata: [
      { label: "Kalibar", value: "12/76" },
      { label: "Cijev", value: "71 cm" },
      { label: "Čokovi", value: "5 Optima-Choke HP" },
    ],
  },
  {
    id: "4",
    name: "Pulsar Krypton 2 FXG50",
    brand: "Pulsar",
    category: "Termalni uređaji",
    sku: "PUL-KRYP-2",
    price: 3450.0,
    status: "new",
    isRegulated: false,
    image: "/images/products/pulsar-krypton.png",
    galleryImages: [
      "/images/products/pulsar-krypton.png",
      "/images/products/vortex-venom.png",
      "/images/categories/thermal.png",
    ],
    shortDescription:
      "Termalni uređaj za promatranje terena s visokim dometom detekcije i stručnom podrškom pri odabiru.",
    availabilityLabel: "Na zalihi",
    metadata: [
      { label: "Senzor", value: "640x480 @ 12 µm" },
      { label: "Domet", value: "2300 m" },
      { label: "Zaslon", value: "AMOLED FHD" },
    ],
  },
  {
    id: "5",
    name: "RWS 30-06 ID Classic 11.7g",
    brand: "RWS",
    category: "Streljivo",
    sku: "RWS-3006-ID",
    price: 85.0,
    status: "in_stock",
    isRegulated: true,
    image: "/images/products/rws-ammo.png",
    galleryImages: [
      "/images/products/rws-ammo.png",
      "/images/products/geco-9mm.png",
      "/images/categories/ammunition.png",
    ],
    shortDescription:
      "Streljivo za registrirane kupce, dostupno isključivo uz provjeru zakonskih uvjeta.",
    availabilityLabel: "Provjera dokumentacije",
    purchaseNote: "Prodaja samo uz važeće isprave i potvrdu trgovine.",
    metadata: [
      { label: "Kalibar", value: "30-06 Sprg" },
      { label: "Težina", value: "11.7g / 180gr" },
      { label: "Tip zrna", value: "ID Classic" },
    ],
  },
  {
    id: "6",
    name: "Geco 9mm Luger FMJ 8.0g",
    brand: "Geco",
    category: "Streljivo",
    sku: "GEC-9MM-FMJ",
    price: 18.5,
    status: "sale",
    salePrice: 15.9,
    isRegulated: true,
    image: "/images/products/geco-9mm.png",
    galleryImages: [
      "/images/products/geco-9mm.png",
      "/images/products/rws-ammo.png",
      "/images/categories/ammunition.png",
    ],
    shortDescription: "Pakiranje streljiva za kupce koji mogu predočiti propisanu dokumentaciju.",
    availabilityLabel: "Provjera dokumentacije",
    purchaseNote: "Kupnja se dovršava u trgovini nakon provjere dokumentacije.",
    metadata: [
      { label: "Kalibar", value: "9x19mm" },
      { label: "Tip zrna", value: "FMJ (Full Metal Jacket)" },
      { label: "Pakiranje", value: "50 kom" },
    ],
  },
  {
    id: "7",
    name: "Härkila Pro Hunter Move Jakna",
    brand: "Härkila",
    category: "Jakne",
    sku: "HAR-PHM-JKT",
    price: 429.0,
    status: "new",
    isRegulated: false,
    image: "/images/products/harkila-jacket.png",
    galleryImages: [
      "/images/products/harkila-jacket.png",
      "/images/products/meindl-boots.png",
      "/images/categories/apparel.png",
    ],
    shortDescription:
      "Robusna terenska jakna s tihom vanjskom tkaninom i krojem za višeslojno nošenje.",
    availabilityLabel: "Na zalihi",
    metadata: [
      { label: "Materijal", value: "Vodoodbojna membrana" },
      { label: "Kroj", value: "Regular fit" },
      { label: "Namjena", value: "Lov i outdoor" },
    ],
  },
  {
    id: "8",
    name: "Meindl Dovre Extreme GTX",
    brand: "Meindl",
    category: "Čizme",
    sku: "MEI-DOV-GTX",
    price: 369.0,
    status: "in_stock",
    isRegulated: false,
    image: "/images/products/meindl-boots.png",
    galleryImages: [
      "/images/products/meindl-boots.png",
      "/images/products/fjallraven-pack.png",
      "/images/categories/apparel.png",
    ],
    shortDescription:
      "Visoke kožne čizme za zahtjevan teren, s čvrstom potporom i zaštitnom membranom.",
    availabilityLabel: "Na zalihi",
    metadata: [
      { label: "Membrana", value: "Gore-Tex" },
      { label: "Potplat", value: "Vibram" },
      { label: "Visina", value: "Visoka čizma" },
    ],
  },
  {
    id: "9",
    name: "Ledlenser MT14 Terenska svjetiljka",
    brand: "Ledlenser",
    category: "Svjetiljke",
    sku: "LED-MT14",
    price: 119.0,
    status: "on_order",
    isRegulated: false,
    image: "/images/products/ledlenser-mt14.png",
    galleryImages: [
      "/images/products/ledlenser-mt14.png",
      "/images/products/fjallraven-pack.png",
      "/images/products/harkila-jacket.png",
    ],
    shortDescription: "Pouzdana punjiva svjetiljka za kamp, izlete i rad na otvorenom.",
    availabilityLabel: "Po narudžbi",
    metadata: [
      { label: "Svjetlosni tok", value: "Do 1000 lm" },
      { label: "Baterija", value: "Punjiva" },
      { label: "Kućište", value: "Aluminij" },
    ],
  },
  {
    id: "10",
    name: "Fjällräven Lappland Hike Pack 45",
    brand: "Fjällräven",
    category: "Ruksaci i torbe",
    sku: "FJR-LAP-45",
    price: 249.0,
    status: "in_stock",
    isRegulated: false,
    image: "/images/products/fjallraven-pack.png",
    galleryImages: [
      "/images/products/fjallraven-pack.png",
      "/images/products/harkila-jacket.png",
      "/images/products/meindl-boots.png",
    ],
    shortDescription:
      "Prostran ruksak za višednevni teren, s organizacijom za odjeću, optiku i osnovnu opremu.",
    availabilityLabel: "Na zalihi",
    metadata: [
      { label: "Volumen", value: "45 l" },
      { label: "Materijal", value: "G-1000 HeavyDuty" },
      { label: "Leđa", value: "Podesivi sustav" },
    ],
  },
]
